---
title: "SharkDistribution"
author: "Max Schwarz"
date: "12 July 2019"
output: html_document
---

```{r load_libraries, include = FALSE}
library(rgbif)
library(tidyverse)
library(maps)
library(leaflet)
library(raster)
library(rgdal)
library(magrittr)
library(devtools)
library(repurrrsive)
```

---
# Mapping Endangered Shark Species Distribution \
\

## 1) Downloading Data from GBIF

<!-- Will explain what I have done in this text chunk -->

```{r dowload_data, include = FALSE}
source("functions.R") #call functions from here

#create vectors (sequence of data elements of same type) for all orders

#Carcharhiniformes

carc <- c('Mustelus fasciatus', 'Cephaloscyllium albipinnum', 'Isogomphodon oxyrhynchus', 'Glyphis garricki', 'Carcharhinus hemiodon', 'Glyphis gangeticus', 'Haploblepharus kistnasamyi', 'Sphyrna mokarran', 'Sphyrna lewini', 'Lamiopsis temminckii', 'Carcharhinus leiodon', 'Holohalaelurus punctatus', 'Mustelus schmitti', 'Holohalaelurus favus', 'Carcharhinus borneensis', 'Eusphyra blochii', 'Carcharhinus dussumieri', 'Glyphis glyphis', 'Hemitriakis leucoperiptera')

#Orectolobiformes

orec <- c('Rhincodon typus', 'Stegostoma fasciatum')

#Squatiniformes

squat <- c('Squatina guggenheim', 'Squatina squatina', 'Squatina formosa', 'Squatina oculata', 'Squatina occulta', 'Squatina argentina', 'Squatina aculeata')

#Squaliformes

squal <- c('Squalus chloroculus', 'Centrophorus harrissoni')

#Lamniformes

lamn <- c('Isurus paucus', 'Isurus oxyrinchus')

#create a vector composed of all orders

species <- c(carc, orec, squat, squal, lamn)

#create a list called distributions, which will house all species data

distributions <- list()
 
for(sp in species) {
  distributions[[sp]] <- import_data(sp)
}

#saving all data in distributions dataframe

saveRDS(distributions, file = "Data/processed/shark_data.rds")
```


## 2) Reading in MPA shapefiles

<!-- Will explain what I have done in this text chunk -->

```{r import_shapefile, include = FALSE}
#reading in the global MPA shapefile

GMPA <- sf::read_sf(dsn = "Data/WDPA July 2019 MPAs", layer = "WDPA_Jul2019_marine-shapefile-polygons")
GMPA2 <- GMPA %>% ggplot2::fortify()

saveRDS(GMPA2, "Data/processed/gmpa2.rds")


```


## 3) Creating distribution maps

Load data

```{r}
source("functions.R")
distributions <- readRDS("Data/processed/shark_data.rds")
distributions_all <- distributions %>% bind_rows()
GMPA2 <- readRDS("Data/processed/gmpa2.rds")

MPA_centre <- sf::st_read("Data/WDPA July 2019 MPAs/WDPA_Jul2019_marine-shapefile-polygons.shp")
GMPA <- sf::read_sf(dsn = "Data/WDPA July 2019 MPAs", layer = "WDPA_Jul2019_marine-shapefile-polygons")

```

Interactive using leaflet:

```{r}
create_leaflet_map("Mustelus fasciatus", distributions)
create_leaflet_map("Cephaloscyllium albipinnum", distributions)
```

All species
```{r}

distributions %>% bind_rows() %>% 
		leaflet() %>%
    addTiles() %>%
    addCircleMarkers(lat = ~latitude, lng = ~longitude, radius = 6, stroke = FALSE, 
                     label = ~species_name, fillOpacity = 0.5)

#(how to colour by species?)
```


Static maps using ggplot

```{r}
world <- map_data("world")
my_map <- 
	ggplot() + geom_map(data=world, map=world,
                    aes(x=long, y=lat, map_id=region),
                    color="white", fill="#7f7f7f", size=0.05, alpha=1/4) +
#       geom_sf(data = GMPA2 %>% slice(1:10), aes(colour="orange")) +
       geom_point(data = distributions[["Cephaloscyllium albipinnum"]], aes(x = longitude, y = latitude))
```

Plot of an MPA:
```{r}
ggplot() + geom_sf(data = GMPA2 %>% slice(1), aes(colour="orange"))
```

Plot of two MPAs:

```{r}
ggplot() + geom_sf(data = GMPA2 %>% slice(1:2), aes(colour="orange"))

```


A function for plotting distributions:

```{r}
plot_species_distn <- function(species_name, distributions) {
world <- map_data("world")
	ggplot() + geom_map(data=world, map=world,
                    aes(x=long, y=lat, map_id=region),
                    color="white", fill="#7f7f7f", size=0.05, alpha=1/4) +
       geom_point(data = distributions[[species_name]], aes(x = longitude, y = latitude))
     }

plot_species_distn("Cephaloscyllium albipinnum", distributions)
plot_species_distn('Mustelus fasciatus', distributions)


ggplot() + 
	geom_map(data=world, map=world,
                    aes(x=long, y=lat, map_id=region),
                    color="white", fill="#7f7f7f", size=0.05, alpha=1/4) +
  geom_point(data = distributions_all, aes(x = longitude, y = latitude)) + 
  facet_wrap(~species_name)
  
```

Using leaflet on polygons:

```{r}

leaflet(GMPA2 %>% slice(1:100)) %>% 
	addTiles() %>% 
	addPolygons()

```


